### ISSUE TITLE
Linking issue with `cc`

### ISSUE THREAD

**Issue by drbh** [007vasy/solana-bigtable-decode#1]
@007vasy I can't seem to replicate the same linking issue, can you share the steps you're doing to reproduce this issue?

Also what hardware / rust / python versions are you using to build this code?

PS: we should add some python scripts that import and test the functions as a way to test the integrations from the Python side

**Comment by 007vasy** [comment]
reproduce (sadly you would need access to a solana table, I wlll create a unit test also)
https://github.com/007vasy/solana-bigtable-decode/blob/c6038788df455e07c62821bfe25c244a8d68e8df/integration-tests-python/sanity_check_test.py#L43

`maturin develop && pytest`  to reproduce the issue

Python 3.8
Ubuntu 20.04
rustc 1.59.0 (9d1b2106e 2022-02-23)
cargo 1.59.0 (49d8809dc 2022-02-10)

**Comment by drbh** [comment]
darn, it's hard for me to retest this since I cannot access the data. I can't seem to reproduce the issue, but based on your description is suggests it's related to linking your `cc` complier with Rust in some way.

Maybe installing a newer version of `gcc` will help? Also i've seem similar Rust linking issues fixed with `sudo apt install gcc-multilib` see: https://github.com/rust-lang/rust/issues/25289#issuecomment-458352264

**Comment by 007vasy** [comment]
yup I tried that, I will create a unit test and ask you again, sorry for taking up your time

**Comment by drbh** [comment]
no worries! It's great to chat with you and try to help with some Rust stuff 👨‍🔬 🦀

**Comment by 007vasy** [comment]
hey @drbh I reproduced the error with a Unit test:
https://github.com/007vasy/solana-bigtable-decode/blob/demo/bigtable-iteraction-with-simple-func/src/lib.rs#L124

if you uncomment line 128 and 129 you will see the error

**Comment by drbh** [comment]
@007vasy thanks for the update! I got the error and I think I have a fix (at least for OSX, but I think you can make a few changes for Ubuntu).

I fixed the issue on my machine by adding a `.cargo` folder and a file inside of it named `config`

it looks like:
```
.cargo
└── config
```

the `config` file contains the following 

```toml
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

I didn't want to fork and open a PR since I'm not sure if this will solve your issue on ubuntu, but try it out 🙂

**Comment by 007vasy** [comment]
thanks a 1000 :D
